/*----------------------------------------------------*
 * This file is automatically generated. DO NOT EDIT! *
 *----------------------------------------------------*/
import type { StoryObj, Meta } from '@storybook/react';
import { Button } from './Button';
type Story = StoryObj<typeof Button>;
const _Button: Story = {
  args: {
    children: 'Button'
  }
};

/**
 * This metadata JSDoc should still be present in the output
 */
const meta: Meta<typeof Button> = {
  component: Button,
  tags: ['snapshot']
};
export default meta;
// Generated combinations of the known parameter variations
const __variants = {
  primary: {
    variant: "primary",
    fullWidth: false
  },
  "primary-fullWidth": {
    variant: "primary",
    fullWidth: true
  },
  secondary: {
    variant: "secondary",
    fullWidth: false
  },
  "secondary-fullWidth": {
    variant: "secondary",
    fullWidth: true
  },
  tertiary: {
    variant: "tertiary",
    fullWidth: false
  },
  "tertiary-fullWidth": {
    variant: "tertiary",
    fullWidth: true
  }
};
const __baseStory = _Button;
/*
 * primary
 */
export const Primary = {
  ...__baseStory,
  args: {
    ...__baseStory.args,
    ...__variants["primary"]
  }
};
/*
 * primary-fullWidth
 */
export const PrimaryFullWidth = {
  ...__baseStory,
  args: {
    ...__baseStory.args,
    ...__variants["primary-fullWidth"]
  }
};
/*
 * secondary
 */
export const Secondary = {
  ...__baseStory,
  args: {
    ...__baseStory.args,
    ...__variants["secondary"]
  }
};
/*
 * secondary-fullWidth
 */
export const SecondaryFullWidth = {
  ...__baseStory,
  args: {
    ...__baseStory.args,
    ...__variants["secondary-fullWidth"]
  }
};
/*
 * tertiary
 */
export const Tertiary = {
  ...__baseStory,
  args: {
    ...__baseStory.args,
    ...__variants["tertiary"]
  }
};
/*
 * tertiary-fullWidth
 */
export const TertiaryFullWidth = {
  ...__baseStory,
  args: {
    ...__baseStory.args,
    ...__variants["tertiary-fullWidth"]
  }
};