packages:
  - '@internal/*'
  - '@udir-design/*'
  - design-tokens
  - test-apps/*

catalog:
  '@commitlint/cli': ^20.0.0
  '@commitlint/config-conventional': ^20.0.0
  '@commitlint/types': ^20.0.0
  '@digdir/designsystemet': 1.6.0
  '@digdir/designsystemet-css': 1.6.0
  '@digdir/designsystemet-react': 1.6.0
  '@eslint/compat': ^1.4.0
  '@eslint/eslintrc': ^3.3.1
  '@eslint/js': ^9.36.0
  '@navikt/aksel-icons': ^7.32.0
  '@nx/azure-cache': ^4.0.0
  '@nx/eslint': 21.4.0
  '@nx/eslint-plugin': 21.4.0
  '@storybook/addon-a11y': ^9.1.8
  '@storybook/addon-docs': ^9.1.8
  '@storybook/addon-vitest': ^9.1.8
  '@storybook/react-vite': ^9.1.8
  '@swc-node/register': ^1.11.1
  '@swc/core': ^1.13.5
  '@swc/helpers': ^0.5.17
  '@testing-library/react': ^16.3.0
  '@types/diffable-html': ^5.0.2
  '@types/mdast': ^4.0.4
  '@types/micromatch': ^4.0.9
  '@types/node': ^24.5.2
  '@types/ramda': ^0.30.2
  '@types/react': ^19.1.14
  '@types/react-dom': ^19.1.9
  '@types/remark-heading-id': ^1.0.0
  '@types/yargs': ^17.0.33
  '@typescript-eslint/eslint-plugin': ^8.44.1
  '@typescript-eslint/parser': ^8.44.1
  '@vitejs/plugin-react-swc': ^4.1.0
  '@vitest/browser': ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  autoprefixer: ^10.4.21
  axe-core: ^4.10.3
  axe-playwright: ^2.2.2
  chromatic: ^13.2.1
  clsx: 2.1.1
  cssnano: ^7.1.1
  diffable-html: ^6.0.1
  eslint: ^9.36.0
  eslint-config-next: ^14.2.33
  eslint-config-prettier: 10.1.1
  eslint-plugin-import: ^2.32.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-storybook: ^9.1.8
  fuse.js: ^7.1.0
  hast-util-from-html: ^2.0.3
  hast-util-is-element: ^3.0.0
  hast-util-to-html: ^9.0.5
  highcharts: ^12.4.0
  highcharts-react-official: ^3.2.2
  husky: ^9.1.7
  jsdom: ^27.0.0
  just-pnpm: 1.0.2
  madge: ^8.0.0
  markdown-to-jsx: ^7.7.13
  mdast-util-to-hast: ^13.2.0
  micromatch: ^4.0.8
  next: ^14.2.33
  nx: 21.4.0
  playwright: ^1.55.1
  postcss: ^8.5.6
  postcss-cli: ^11.0.1
  postcss-import: ^16.1.1
  postcss-import-ext-glob: ^2.1.1
  postcss-load-config: ^6.0.1
  postcss-nesting: ^13.0.2
  prettier: 3.6.2
  ramda: ^0.31.3
  react: ^19.1.1
  react-dom: ^19.1.1
  react-hook-form: ^7.63.0
  react-style-stringify: ^1.2.0
  remark-gfm: ^4.0.1
  remark-heading-id: ^1.0.1
  remark-parse: ^11.0.0
  remark-stringify: ^11.0.0
  rimraf: ^6.0.1
  sass: ^1.93.2
  storybook: ^9.1.8
  storybook-addon-pseudo-states: ^9.1.8
  storybook-addon-tag-badges: ^2.0.2
  ts-node: ^10.9.2
  tslib: ^2.8.1
  tsup: ^8.5.0
  tsx: ^4.20.6
  typescript: ^5.9.2
  typescript-eslint: ^8.44.1
  unified: ^11.0.5
  unist-util-remove: ^4.0.0
  unist-util-visit: ^5.0.0
  vite: ^7.1.7
  vite-plugin-dts: ^4.5.4
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.4
  yargs: ^18.0.0

catalogMode: strict

catalogs:
  react18:
    '@types/react': ^18.3.24
    '@types/react-dom': ^18.3.7
    react: ^18.3.1
    react-dom: ^18.3.1

cleanupUnusedCatalogs: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@digdir/*'

packageExtensions:
  '@navikt/aksel-icons':
    peerDependencies:
      react: '>=18.3.1 || ^19.0.0'
    peerDependenciesMeta:
      react:
        optional: true

useNodeVersion: 24.6.0
