packages:
  - '@internal/*'
  - '@udir-design/*'
  - design-tokens
  - test-apps/*

catalog:
  '@babel/types': ^7.28.5
  '@commitlint/cli': ^20.3.0
  '@commitlint/config-conventional': ^20.3.0
  '@commitlint/types': ^20.2.0
  '@digdir/designsystemet': 1.9.0
  '@digdir/designsystemet-css': 1.9.0
  '@digdir/designsystemet-react': 1.9.0
  '@digdir/designsystemet-types': ^1.9.0
  '@eslint/compat': ^1.4.1
  '@eslint/eslintrc': ^3.3.3
  '@eslint/js': ^9.39.2
  '@figma/rest-api-spec': ^0.35.0
  '@hookform/resolvers': 5.2.2
  '@navikt/aksel-icons': ^7.36.0
  '@next/eslint-plugin-next': ^16.1.1
  '@nx/azure-cache': ^5.0.0
  '@nx/eslint': 22.3.3
  '@nx/eslint-plugin': 22.3.3
  '@storybook/addon-a11y': ^10.1.11
  '@storybook/addon-docs': ^10.1.11
  '@storybook/addon-vitest': ^10.1.11
  '@storybook/react-vite': ^10.1.11
  '@svgr/cli': 8.1.0
  '@svgr/core': ^8.1.0
  '@swc-node/register': ^1.11.1
  '@swc/core': ^1.15.8
  '@swc/helpers': ^0.5.18
  '@testing-library/react': ^16.3.1
  '@types/diffable-html': ^5.0.2
  '@types/mdast': ^4.0.4
  '@types/micromatch': ^4.0.10
  '@types/node': ^24.10.4
  '@types/ramda': ^0.31.1
  '@types/react': ^19.2.6
  '@types/react-dom': ^19.2.3
  '@types/remark-heading-id': ^1.0.0
  '@types/yargs': ^17.0.35
  '@typescript-eslint/eslint-plugin': ^8.51.0
  '@typescript-eslint/parser': ^8.51.0
  '@typescript/native-preview': 7.0.0-dev.20251220.1
  '@u-elements/u-details': ^0.1.5
  '@vitejs/plugin-react-swc': ^4.2.2
  '@vitest/browser': ^4.0.16
  '@vitest/browser-playwright': ^4.0.16
  '@vitest/coverage-v8': ^4.0.16
  '@vitest/ui': ^4.0.16
  autoprefixer: ^10.4.23
  axe-core: ^4.11.0
  axe-playwright: ^2.2.2
  camelcase: ^9.0.0
  chromatic: ^13.3.4
  clsx: 2.1.1
  cssnano: ^7.1.2
  diffable-html: ^6.0.1
  eslint: ^9.39.2
  eslint-config-next: ^16.1.1
  eslint-config-prettier: 10.1.8
  eslint-plugin-import: ^2.32.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-storybook: ^10.1.11
  fast-glob: ^3.3.3
  fuse.js: ^7.1.0
  hast-util-from-html: ^2.0.3
  hast-util-is-element: ^3.0.0
  hast-util-to-html: ^9.0.5
  highcharts: ^12.4.0
  highcharts-react-official: ^3.2.3
  husky: ^9.1.7
  js-yaml: ^4.1.1
  jsdom: ^27.4.0
  lodash-es: ^4.17.22
  madge: ^8.0.0
  markdown-to-jsx: ^7.7.17
  mdast-util-to-hast: ^13.2.1
  micromatch: ^4.0.8
  next: ^16.1.1
  nx: 22.3.3
  parcel: ^2.16.3
  playwright: ^1.57.0
  postcss: ^8.5.6
  postcss-cli: ^11.0.1
  postcss-easy-import: ^4.0.0
  postcss-load-config: ^6.0.1
  postcss-nesting: ^13.0.2
  prettier: 3.7.4
  ramda: ^0.32.0
  react: ^19.2.0
  react-dom: ^19.2.0
  react-dropzone: ^14.3.8
  react-hook-form: ^7.70.0
  react-style-stringify: ^1.2.0
  remark-gfm: ^4.0.1
  remark-heading-id: ^1.0.1
  remark-parse: ^11.0.0
  remark-stringify: ^11.0.0
  rimraf: ^6.1.2
  sass: ^1.97.1
  sharp: ^0.34.5
  shx: ^0.4.0
  storybook: ^10.1.11
  storybook-addon-pseudo-states: ^10.1.11
  svgo: 4.0.0
  ts-node: ^10.9.2
  tslib: ^2.8.1
  tsup: ^8.5.1
  tsx: ^4.21.0
  type-fest: ^5.2.0
  typedoc: ^0.28.15
  typescript: ^5.9.3
  typescript-eslint: ^8.51.0
  unified: ^11.0.5
  unist-util-remove: ^4.0.0
  unist-util-visit: ^5.0.0
  vite: ^7.3.0
  vite-plugin-dts: ^4.5.4
  vite-tsconfig-paths: ^5.1.4
  vitest: ^4.0.16
  yargs: ^18.0.0
  zod: ^4.3.5

catalogMode: strict

catalogs:
  react18:
    '@types/react': ^18.3.27
    '@types/react-dom': ^18.3.7
    react: ^18.3.1
    react-dom: ^18.3.1

cleanupUnusedCatalogs: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@digdir/*'

packageExtensions:
  '@navikt/aksel-icons':
    peerDependencies:
      '@types/react': ^18.3.11 || ^19.0.0
      react: ^18.3.1 || ^19.0.0
    peerDependenciesMeta:
      '@types/react':
        optional: true
      react:
        optional: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@6.3.1
  - eslint-import-resolver-typescript@3.10.1
  - detect-port@1.6.1

useNodeVersion: 24.10.0

verifyDepsBeforeRun: prompt
