useNodeVersion: 24.6.0
packages:
  - '@internal/*'
  - '@udir-design/*'
  - design-tokens
  - test-apps/*
packageExtensions:
  '@navikt/aksel-icons':
    peerDependencies:
      react: '>=18.3.1 || ^19.0.0'
    peerDependenciesMeta:
      react:
        optional: true
minimumReleaseAge: 1440 # packages must be at least 1 day old, to allow time for supply-chain attacks to be detected
minimumReleaseAgeExclude:
  - '@digdir/designsystemet'
  - '@digdir/designsystemet-css'
  - '@digdir/designsystemet-react'
