useNodeVersion: 22.14.0
packages:
  - '@internal/*'
  - '@udir-design/*'
  - design-tokens
  - test-apps/*
onlyBuiltDependencies:
  - just-pnpm
  - nx
ignoredBuiltDependencies:
  - '@bundled-es-modules/glob'
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - msw
  - style-dictionary
