packages:
  - '@internal/*'
  - '@udir-design/*'
  - design-tokens
  - test-apps/*

catalog:
  '@commitlint/cli': ^20.1.0
  '@commitlint/config-conventional': ^20.0.0
  '@commitlint/types': ^20.0.0
  '@digdir/designsystemet': 1.7.3
  '@digdir/designsystemet-css': 1.7.3
  '@digdir/designsystemet-react': 1.7.3
  '@eslint/compat': ^1.4.1
  '@eslint/eslintrc': ^3.3.1
  '@eslint/js': ^9.39.1
  '@navikt/aksel-icons': ^7.33.3
  '@next/eslint-plugin-next': ^14.2.33
  '@nx/azure-cache': ^4.0.0
  '@nx/eslint': 21.4.0
  '@nx/eslint-plugin': 21.4.0
  '@storybook/addon-a11y': ^9.1.16
  '@storybook/addon-docs': ^9.1.16
  '@storybook/addon-vitest': ^9.1.16
  '@storybook/react-vite': ^9.1.16
  '@swc-node/register': ^1.11.1
  '@swc/core': ^1.15.2
  '@swc/helpers': ^0.5.17
  '@testing-library/react': ^16.3.0
  '@types/diffable-html': ^5.0.2
  '@types/mdast': ^4.0.4
  '@types/micromatch': ^4.0.10
  '@types/node': ^24.10.1
  '@types/ramda': ^0.30.2
  '@types/react': ^19.2.5
  '@types/react-dom': ^19.2.3
  '@types/remark-heading-id': ^1.0.0
  '@types/yargs': ^17.0.35
  '@typescript-eslint/eslint-plugin': ^8.46.4
  '@typescript-eslint/parser': ^8.46.4
  '@vitejs/plugin-react-swc': ^4.2.2
  '@vitest/browser': ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  autoprefixer: ^10.4.22
  axe-core: ^4.11.0
  axe-playwright: ^2.2.2
  chromatic: ^13.3.3
  clsx: 2.1.1
  cssnano: ^7.1.2
  diffable-html: ^6.0.1
  eslint: ^9.39.1
  eslint-config-next: ^14.2.33
  eslint-config-prettier: 10.1.1
  eslint-plugin-import: ^2.32.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-storybook: ^9.1.16
  fuse.js: ^7.1.0
  hast-util-from-html: ^2.0.3
  hast-util-is-element: ^3.0.0
  hast-util-to-html: ^9.0.5
  highcharts: ^12.4.0
  highcharts-react-official: ^3.2.3
  husky: ^9.1.7
  jsdom: ^27.2.0
  just-pnpm: 1.0.2
  madge: ^8.0.0
  markdown-to-jsx: ^7.7.17
  mdast-util-to-hast: ^13.2.0
  micromatch: ^4.0.8
  next: ^14.2.33
  nx: 21.4.0
  parcel: ^2.16.1
  playwright: ^1.56.1
  postcss: ^8.5.6
  postcss-cli: ^11.0.1
  postcss-easy-import: ^4.0.0
  postcss-load-config: ^6.0.1
  postcss-nesting: ^13.0.2
  prettier: 3.6.2
  ramda: ^0.31.3
  react: ^19.2.0
  react-dom: ^19.2.0
  react-hook-form: ^7.66.0
  react-style-stringify: ^1.2.0
  remark-gfm: ^4.0.1
  remark-heading-id: ^1.0.1
  remark-parse: ^11.0.0
  remark-stringify: ^11.0.0
  rimraf: ^6.1.0
  sass: ^1.94.0
  storybook: ^9.1.16
  storybook-addon-pseudo-states: ^9.1.16
  storybook-addon-tag-badges: ^2.0.4
  svgo: ^4.0.0
  ts-node: ^10.9.2
  tslib: ^2.8.1
  tsup: ^8.5.1
  tsx: ^4.20.6
  type-fest: ^5.2.0
  typescript: ^5.9.3
  typescript-eslint: ^8.46.4
  unified: ^11.0.5
  unist-util-remove: ^4.0.0
  unist-util-visit: ^5.0.0
  vite: ^7.2.2
  vite-plugin-dts: ^4.5.4
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.4
  yargs: ^18.0.0

catalogMode: strict

catalogs:
  react18:
    '@types/react': ^18.3.26
    '@types/react-dom': ^18.3.7
    react: ^18.3.1
    react-dom: ^18.3.1

cleanupUnusedCatalogs: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@digdir/*'

packageExtensions:
  '@navikt/aksel-icons':
    peerDependencies:
      '@types/react': ^18.3.11 || ^19.0.0
      react: ^18.3.1 || ^19.0.0
    peerDependenciesMeta:
      '@types/react':
        optional: true
      react:
        optional: true

useNodeVersion: 24.10.0
