name: Prepare pnpm & Nx
description: Installs pnpm, sets up the pnpm cache, and sets the Nx hashes
inputs:
  registry-url:
    description: |
      Optional registry to set up for auth. Will set the registry in a project level
      .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN.
    default: ''

runs:
  using: 'composite'
  steps:
    # Note: pnpm version is set in package.json "packageManager"
    - name: Install pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

    # Cache node_modules
    # Note: node version is set in package.json "engines.node"
    - uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'
        cache: 'pnpm'
        registry-url: ${{ inputs.registry-url }}

    - run: pnpm install
      shell: bash

    - uses: nrwl/nx-set-shas@dbe0650947e5f2c81f59190a38512cf49126fe6b # v4.3.0
      with:
        main-branch-name: ${{ github.base_ref || github.ref_name }}
