#!/usr/bin/env -S pnpm tsx

/*
 * Applies our own token values from `src-overrides/` to the files generated by
 * `designsystemet tokens create`. Runs as the `postcreate` script.
 */

import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const OVERRIDES = [
  {
    target: 'src/semantic/style.json',
    patch: 'src-overrides/semantic/style.json',
  },
];

type JsonObject = { [key: string]: unknown };

const isPlainObject = (value: unknown): value is JsonObject =>
  typeof value === 'object' && value !== null && !Array.isArray(value);

/**
 * Recursively copies the values in `patch` into `target`, replacing only the individual values in
 * the patch. Throws if a path in `patch` is missing from `target`, or if one side has an object
 * where the other has a value. That way an upstream rename fails loudly instead of adding an
 * orphan token.
 */
function applyPatch(
  target: JsonObject,
  patch: JsonObject,
  file: string,
  keyPath: string[] = [],
) {
  for (const [key, value] of Object.entries(patch)) {
    const here = [...keyPath, key];
    if (!Object.hasOwn(target, key)) {
      throw new Error(`Override "${here.join('.')}" does not exist in ${file}`);
    }
    const current = target[key];
    if (isPlainObject(value) && isPlainObject(current)) {
      applyPatch(current, value, file, here);
    } else if (isPlainObject(value) || isPlainObject(current)) {
      throw new Error(
        `Override "${here.join('.')}" does not match the structure of ${file}`,
      );
    } else {
      target[key] = value;
    }
  }
}

for (const { target, patch } of OVERRIDES) {
  const targetFile = path.resolve(target);
  const tokens: unknown = JSON.parse(await readFile(targetFile, 'utf8'));
  const overrides: unknown = JSON.parse(
    await readFile(path.resolve(patch), 'utf8'),
  );
  if (!isPlainObject(tokens) || !isPlainObject(overrides)) {
    throw new Error(`Expected JSON objects in ${target} and ${patch}`);
  }
  applyPatch(tokens, overrides, target);
  // Match the formatting of `designsystemet tokens create` (2 spaces, no trailing newline)
  await writeFile(targetFile, JSON.stringify(tokens, null, 2), 'utf8');
  console.log(`✔︎ Applied ${patch} to ${target}`);
}
