import { defineConfig } from 'oxlint';
import { TS_FILES, coreRulesForTypeScript } from '../../oxlint.shared.ts';

// Standalone config (no `extends`), so `categories`/`env` are declared here.
export default defineConfig({
  plugins: ['nextjs', 'typescript'],
  categories: {
    correctness: 'off',
  },
  env: {
    builtin: true,
  },
  // `.next`, `out`, and `next-env.d.ts` are already covered by `.gitignore`.
  ignorePatterns: ['build/**'],
  rules: {
    'no-array-constructor': 'error',
    'no-unused-expressions': 'warn',
    'no-unused-vars': 'warn',
    // Next.js-specific rules.
    'nextjs/google-font-display': 'warn',
    'nextjs/google-font-preconnect': 'warn',
    'nextjs/next-script-for-ga': 'warn',
    'nextjs/no-async-client-component': 'warn',
    'nextjs/no-before-interactive-script-outside-document': 'warn',
    'nextjs/no-css-tags': 'warn',
    'nextjs/no-head-element': 'warn',
    'nextjs/no-html-link-for-pages': 'error',
    'nextjs/no-img-element': 'warn',
    'nextjs/no-page-custom-font': 'warn',
    'nextjs/no-styled-jsx-in-document': 'warn',
    'nextjs/no-sync-scripts': 'error',
    'nextjs/no-title-in-document-head': 'warn',
    'nextjs/no-typos': 'warn',
    'nextjs/no-unwanted-polyfillio': 'warn',
    'nextjs/inline-script-id': 'error',
    'nextjs/no-assign-module-variable': 'error',
    'nextjs/no-document-import-in-page': 'error',
    'nextjs/no-duplicate-head': 'error',
    'nextjs/no-head-import-in-document': 'error',
    'nextjs/no-script-component-in-head': 'error',
    // TypeScript-specific rules.
    'typescript/ban-ts-comment': 'error',
    'typescript/no-duplicate-enum-values': 'error',
    'typescript/no-empty-object-type': 'error',
    'typescript/no-explicit-any': 'error',
    'typescript/no-extra-non-null-assertion': 'error',
    'typescript/no-misused-new': 'error',
    'typescript/no-namespace': 'error',
    'typescript/no-non-null-asserted-optional-chain': 'error',
    'typescript/no-require-imports': 'error',
    'typescript/no-this-alias': 'error',
    'typescript/no-unnecessary-type-constraint': 'error',
    'typescript/no-unsafe-declaration-merging': 'error',
    'typescript/no-unsafe-function-type': 'error',
    'typescript/no-wrapper-object-types': 'error',
    'typescript/prefer-as-const': 'error',
    'typescript/prefer-namespace-keyword': 'error',
    'typescript/triple-slash-reference': 'error',
  },
  overrides: [
    {
      // React + jsx-a11y + import rules for Next.js app source.
      files: ['**/*.{js,jsx,mjs,ts,tsx,mts,cts}'],
      plugins: ['react', 'import', 'jsx-a11y'],
      env: {
        browser: true,
        node: true,
      },
      globals: {
        AudioWorkletGlobalScope: 'readonly',
        AudioWorkletProcessor: 'readonly',
        currentFrame: 'readonly',
        currentTime: 'readonly',
        registerProcessor: 'readonly',
        sampleRate: 'readonly',
        WorkletGlobalScope: 'readonly',
      },
      rules: {
        'react/display-name': 'error',
        'react/jsx-key': 'error',
        'react/jsx-no-comment-textnodes': 'error',
        'react/jsx-no-duplicate-props': 'error',
        'react/jsx-no-target-blank': 'off',
        'react/jsx-no-undef': 'error',
        'react/no-children-prop': 'error',
        'react/no-danger-with-children': 'error',
        'react/no-direct-mutation-state': 'error',
        'react/no-find-dom-node': 'error',
        'react/no-is-mounted': 'error',
        'react/no-render-return-value': 'error',
        'react/no-string-refs': 'error',
        'react/no-unescaped-entities': 'error',
        'react/no-unknown-property': 'off',
        'react/no-unsafe': 'off',
        'react/react-in-jsx-scope': 'off',
        'import/no-anonymous-default-export': 'warn',
        'jsx-a11y/alt-text': [
          'warn',
          {
            elements: ['img'],
            img: ['Image'],
          },
        ],
        'jsx-a11y/aria-props': 'warn',
        'jsx-a11y/aria-proptypes': 'warn',
        'jsx-a11y/aria-unsupported-elements': 'warn',
        'jsx-a11y/role-has-required-aria-props': 'warn',
        'jsx-a11y/role-supports-aria-props': 'warn',
        'react/rules-of-hooks': 'error',
        'react/exhaustive-deps': 'warn',
      },
    },
    {
      // Core rule overrides for TypeScript files (turn off ones TS covers).
      files: TS_FILES,
      rules: coreRulesForTypeScript,
    },
  ],
});
