name: Deploy testapp to Azure

on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  APP_PATH: test-apps/nextjs
  IMAGE_NAME: ghcr.io/utdanningsdirektoratet/designsystem-testapp

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check if deploy should be initiated
    outputs:
      should_deploy: ${{ steps.should_deploy.outputs.should_deploy }}
    permissions:
      contents: read
      actions: 'read'
      pull-requests: 'read'
    steps:
      - name: Check out repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          filter: tree:0

      - uses: ./.github/actions/pnpm-setup

      - name: Determine whether to deploy
        id: should_deploy
        run: |
          IS_NEXTJS_AFFECTED=$(./@internal/build-tools/bin/is-project-affected.sh test-app-nextjs)
          IS_WORKFLOW_MODIFIED=$(./@internal/build-tools/bin/is-file-modified.sh .github/workflows/azure-testapp-deploy.yml)
          echo "Is the Next.js test app affected? $IS_NEXTJS_AFFECTED"
          echo "Is the deployment workflow modified? $IS_WORKFLOW_MODIFIED"
          echo "Is the deploy triggered through a manual workflow dispatch? $IS_DISPATCH"
          ($IS_DISPATCH || $IS_NEXTJS_AFFECTED || $IS_WORKFLOW_MODIFIED) && SHOULD_DEPLOY=true || SHOULD_DEPLOY=false
          echo "Conclusion: should we deploy the test app? $SHOULD_DEPLOY"
          echo "should_deploy=$SHOULD_DEPLOY" >> "$GITHUB_OUTPUT"
        env:
          IS_DISPATCH: ${{ github.event_name == 'workflow_dispatch'}}

  build_and_deploy:
    needs: check
    if: needs.check.outputs.should_deploy == 'true'
    runs-on: ubuntu-latest
    environment: test-app
    name: Build image, push to GHCR, and deploy to Azure Container Apps
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Check out repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Log in to GHCR
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: .
          file: ./test-apps/nextjs/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Log in to Azure
        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@8dff69dac3367c32ceb2690d8f13adbeab462703 # v2
        with:
          containerAppName: ca-designsystem-testapp
          resourceGroup: rg-designsystem-testapp
          imageToDeploy: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          registryUrl: ghcr.io
          targetPort: 3000
