name: Update minor versions
on:
  workflow_dispatch:

env:
  BRANCH_NAME: build/update-minor
jobs:
  update-minor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
