name: Update prettier
on:
  workflow_dispatch:
  schedule:
    # Runs at 02:00, only on Monday
    - cron: 0 2 * * 1

jobs:
  update-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/pnpm-setup
      - name: Configure git user
        run: |
          # Setup the committers identity.
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Check if update is necessary
        run: echo "version=$(pnpm outdated -r prettier --json | jq -r '.prettier.latest // ""')" >> "$GITHUB_OUTPUT"
        id: prettier_info

      - name: Update Prettier and format all files
        if: steps.prettier_info.outputs.version
        id: prettier_run
        run: |
          pnpm update -r --latest prettier
          git commit --all -m "build: update prettier to ${{ steps.prettier_info.outputs.version }}"
          pnpm nx format:write --all
          echo has_changes="$(git diff --stat --exit-code)" >> "$GITHUB_OUTPUT"

      - name: Commit changes and update .git-blame-ignore-revs
        if: steps.prettier_run.outputs.has_changes == 1
        run: |
          git commit --all -m "style: format files with prettier ${{ steps.prettier_info.outputs.version }}"
          echo "# $(git show -s --format='%s')\n$(git rev-parse HEAD)" > .git-blame-ignore-revs
          git commit --all -m "chore: update .git-blame-ignore-revs"

      - name: Create or update pull request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          branch: build/update-prettier
          base: ${{ github.event.repository.default_branch }}
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          title: 'build: update prettier to ${{ steps.prettier_info.outputs.version }}'
          body: Updates prettier to the latest version and formats all files
          draft: always-true
